services:
  app:
    build:
      context: ./docker/app
    init: true
    command: sleep infinity
    volumes:
      - ..:/workspaces/voting-2024:cached

  db:
    image: ghcr.io/denoland/denokv
    init: true
    ports:
      - "4512:4512"
    environment:
      DENO_KV_SQLITE_PATH: /data/denokv.sqlite
      DENO_KV_ACCESS_TOKEN: very-very-secret
    volumes:
      - db-data:/data

volumes:
  db-data:
